# Generated by Django 3.0.8 on 2020-07-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='directory',
            field=models.CharField(default='', max_length=255),
        ),
    ]
