# Generated by Django 3.0.8 on 2020-07-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0002_file_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='directory',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
